version: '3.7'
services:
  redis1:
    container_name: redis1
    image: redis:alpine
  redis2:
    container_name: redis2
    image: redis:alpine
  redis3:
    container_name: redis3
    image: redis:alpine
  sentinel1:
    container_name: sentinel1
    build:
      context: .
      dockerfile: sentinel.Dockerfile
  sentinel2:
    container_name: sentinel2
    build:
      context: .
      dockerfile: sentinel.Dockerfile
  sentinel3:
    container_name: sentinel3
    build:
      context: .
      dockerfile: sentinel.Dockerfile